# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VIVADO/homwork3question2/XADC_test/XADC_test.srcs/sources_1/ip/Adder/Adder.xci
# IP: The module: 'Adder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO/homwork3question2/XADC_test/XADC_test.srcs/sources_1/ip/Adder/Adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adder'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/VIVADO/homwork3question2/XADC_test/XADC_test.srcs/sources_1/ip/Adder/Adder.xci
# IP: The module: 'Adder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO/homwork3question2/XADC_test/XADC_test.srcs/sources_1/ip/Adder/Adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adder'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
