# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Huang Xianmin/Documents/WeChat Files/wxid_p0o17fpz34pq11/FileStorage/File/2023-06/digitalBIGHW/digitalBIGHW/PID_VGA_2.0/PID_VGA_2.0.srcs/sources_1/ip/rom_title/rom_title.xci
# IP: The module: 'rom_title' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Huang Xianmin/Documents/WeChat Files/wxid_p0o17fpz34pq11/FileStorage/File/2023-06/digitalBIGHW/digitalBIGHW/PID_VGA_2.0/PID_VGA_2.0.srcs/sources_1/ip/rom_title/rom_title_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_title'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Huang Xianmin/Documents/WeChat Files/wxid_p0o17fpz34pq11/FileStorage/File/2023-06/digitalBIGHW/digitalBIGHW/PID_VGA_2.0/PID_VGA_2.0.srcs/sources_1/ip/rom_title/rom_title.xci
# IP: The module: 'rom_title' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Huang Xianmin/Documents/WeChat Files/wxid_p0o17fpz34pq11/FileStorage/File/2023-06/digitalBIGHW/digitalBIGHW/PID_VGA_2.0/PID_VGA_2.0.srcs/sources_1/ip/rom_title/rom_title_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_title'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
