# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/fzh/XADC_test/XADC_test.cache/wt [current_project]
set_property parent.project_path C:/Users/fzh/XADC_test/XADC_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/fzh/XADC_test/XADC_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/digitalBIGHW/daolibai.coe
read_verilog -library xil_defaultlib {
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/Abs.v}
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/new/VGA_top.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/bt_uart.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/clk_div.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/pendulum/pendulum.srcs/sources_1/new/clk_divide128.v
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/clk_division.v}
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/clk_gen.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/cmd_parse.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/debouncer.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/pendulum/pendulum.srcs/sources_1/new/divide_clk.v
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/fsm_drp.v}
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/hex_to_bcd.v}
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/lb_ctl.v
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/led.v}
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/meta_harden.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/pendulum/pendulum.srcs/sources_1/new/pendulum.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/pendulum/pendulum.srcs/sources_1/new/pid_top.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/pendulum/pendulum.srcs/sources_1/new/pwm.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/reset_bridge.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/resp_gen.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/rst_gen.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/seg7decimal.v
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/seg_selection.v}
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/switch_convert_16_to_42.v}
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/to_bcd.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/uart_baud_gen.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/uart_rx.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/uart_rx_ctl.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/uart_tx.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/imports/new/uart_tx_ctl.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/new/vga_640_480.v
  C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/sources_1/new/vga_dis_num.v
  {C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/imports/Desktop/数字系统/xadc_release/Design sources/Verilog/top_module.v}
}
read_ip -quiet C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/char_fifo/char_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/char_fifo/char_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc]

read_ip -quiet C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/clk_core/clk_core.xci
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/clk_core/clk_core_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/clk_core/clk_core.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc]

read_ip -quiet C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/Adder/Adder.xci
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/Adder/Adder_ooc.xdc]

read_ip -quiet C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/Multiplier/Multiplier.xci
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/Multiplier/Multiplier_ooc.xdc]

read_ip -quiet C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

read_ip -quiet C:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet C:/Users/fzh/XADC_test/XADC_test.srcs/rom_title/ip/rom_title/rom_title.xci
set_property used_in_implementation false [get_files -all c:/Users/fzh/XADC_test/XADC_test.srcs/rom_title/ip/rom_title/rom_title_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fzh/XADC_test/XADC_test.srcs/constrs_1/imports/Constraints/fsm_xadc.xdc
set_property used_in_implementation false [get_files C:/Users/fzh/XADC_test/XADC_test.srcs/constrs_1/imports/Constraints/fsm_xadc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_module -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
